### ISSUE TITLE
Create Snakemake run config files

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp-cli#10]
**Is your feature request related to a problem? Please describe.**
Write Snakemake run config to file and samples table

**Describe the solution you'd like**
Implement in `run/snakemake.py`

**Additional context**
The variable names used within snakemake (snakemake column) : https://git.scicore.unibas.ch/zavolan_group/pipelines/zarp/-/blob/dev/scripts/prepare_inputs.dict.tsv

**Comment by uniqueg** [comment]
This is the expected format:

```yaml
---
  # Required fields
  samples: "../input_files/samples.tsv"
  output_dir: "results"
  log_dir: "logs"
  cluster_log_dir: "logs/cluster"
  kallisto_indexes: "results/kallisto_indexes"
  salmon_indexes: "results/salmon_indexes"
  star_indexes: "results/star_indexes"
  alfa_indexes: "results/alfa_indexes"
  # Optional fields
  rule_config: "../input_files/rule_config.yaml"
  report_description: "No description provided by user"
  report_logo: "../../images/logo.128px.png"
  report_url: "https://zavolan.biozentrum.unibas.ch/"
  author_name: "NA"
  author_email: "NA"
...
```
