### ISSUE TITLE
Publish ZARP-cli on Bioconda

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp-cli#37]
**Is your feature request related to a problem? Please describe.**

For better visibility in the bioscience community, it is useful if ZARP-cli is available on Bioconda.

**Describe the solution you'd like**

Use the usual procedure to publish ZARP-cli to Bioconda.

**Additional context**

Should implement #36 first.

**Comment by uniqueg** [comment]
This actually can be done without `environment.yml`, using [`conda skeleton pypi`](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html). This generates a `meta.yaml` based off the PyPI repo, which can be used for the initial submission to Bioconda. For subsequent releases to PyPI, Bioconda should then automatically build new versions.

**Comment by fgypas** [comment]
For this a PR to bioconda would be enough I think. Let me know if I should open a PR to them, or you will have a look at it?

**Comment by fgypas** [comment]
Here is an example:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/zgtf/meta.yaml

**Comment by fgypas** [comment]
I opened a PR by the way:
https://github.com/bioconda/bioconda-recipes/pull/39910

**Comment by uniqueg** [comment]
Hi @fgypas. `conda skeleton` generated this:

```yaml
{% set name = "zarp" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0defdec6fe8dabf66d40f2f4d16dfc2619f509f11763356908af3be51ca049ab

build:
  number: 0
  entry_points:
    - zarp = zarp.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - addict ==2.4.0
    - bidict ==0.22.0
    - email-validator ==1.2.1
    - jsonref ==0.2
    - pandas ==1.3.5
    - pip
    - pydantic ==1.9.2
    - pydantic-collections ==0.3.0
    - pygments ==2.8.0
    - python
    - rich ==12.5.1
  run:
    - addict ==2.4.0
    - bidict ==0.22.0
    - email-validator ==1.2.1
    - jsonref ==0.2
    - pandas ==1.3.5
    - pydantic ==1.9.2
    - pydantic-collections ==0.3.0
    - pygments ==2.8.0
    - python
    - rich ==12.5.1

test:
  imports:
    - tests
    - tests.config
    - zarp
    - zarp.config
    - zarp.extensions
    - zarp.run
  commands:
    - zarp --help

about:
  home: "https://git.scicore.unibas.ch/zavolan_group/tools/zarp-cli"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "User-friendly command-line interface for the ZARP RNA-Seq analysis pipeline"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
```

I think the `build: noarch: python` is a good addition, but the `build: entry_points` and the additional tests I think would be nice to have.

Note that the value of `about: home` is wrong. I wanted to fix that first in `setup.py` before opening a PR. And also add the appropriate metadata to `setup()` so that `doc_url` is automatically populated.

**Comment by uniqueg** [comment]
(I have no idea what's the significance of `requirements: host` vs `requirements: run`, maybe the way you do it is enough)

**Comment by fgypas** [comment]
I like the results from the skeleton.

So I will add in the PR the test:
```
test:
  imports:
    - tests
    - tests.config
    - zarp
    - zarp.config
    - zarp.extensions
    - zarp.run
  commands:
    - zarp --help
```
And the summary: 
`  summary: "User-friendly command-line interface for the ZARP RNA-Seq analysis pipeline"`
